# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QSizePolicy


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 612)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LoadCSV = QtWidgets.QPushButton(parent=self.centralwidget)
        self.LoadCSV.setObjectName("LoadEtsyCSV")
        self.horizontalLayout_2.addWidget(self.LoadCSV)
        self.CreatePinCSV = QtWidgets.QPushButton(parent=self.centralwidget)
        self.CreatePinCSV.setObjectName("CreatePintrestCSVs")
        self.horizontalLayout_2.addWidget(self.CreatePinCSV)
        #self.ConvertPDFs = QtWidgets.QPushButton(parent=self.centralwidget)
        #self.ConvertPDFs.setObjectName("ConvertPDFs")
        #self.horizontalLayout_2.addWidget(self.ConvertPDFs)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.Keywords = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.Keywords.setObjectName("Keywords")
        #self.Keywords.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        self.Keywords.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
        self.Keywords.setPlaceholderText("Add keywords separated by commas here. They are assumed to be single \
            works so all white space will be deleted")
        self.verticalLayout.addWidget(self.Keywords)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Image = QtWidgets.QLabel(parent=self.centralwidget)
        self.Image.setObjectName("Image")
        self.verticalLayout_3.addWidget(self.Image)
        self.ImageTitle = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ImageTitle.setText("")
        self.ImageTitle.setObjectName("ImageTitle")
        self.verticalLayout_3.addWidget(self.ImageTitle)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Previous = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Previous.setObjectName("Previous")
        self.horizontalLayout_4.addWidget(self.Previous)
        self.ImageIndex = QtWidgets.QLabel(parent=self.centralwidget)
        self.ImageIndex.setText("")
        self.ImageIndex.setObjectName("ImageIndex")
        self.horizontalLayout_4.addWidget(self.ImageIndex)
        self.Next = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Next.setObjectName("Next")
        self.horizontalLayout_4.addWidget(self.Next)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.Save = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Save.setObjectName("Save")
        self.verticalLayout_3.addWidget(self.Save)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 23))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(parent=self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Etsy2Pinterest converter"))
        self.LoadCSV.setText(_translate("MainWindow", "Load CSV\'s"))
        self.CreatePinCSV.setText(_translate("MainWindow", "Create Pintrest CSV\'s"))
        #self.ConvertPDFs.setText(_translate("MainWindow", "Convert PDF\'s"))
        self.Image.setText(_translate("MainWindow", ""))
        self.ImageTitle.setPlaceholderText(_translate("MainWindow", "Title. Don't include image sizes"))
        self.Previous.setText(_translate("MainWindow", "Previous"))
        self.Next.setText(_translate("MainWindow", "Next"))
        self.Save.setText(_translate("MainWindow", "Save All"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
